Switch to HTTP for the fsapp endpoint
opendata-stuttgart/sensors-software pull request #736
Opened 2020-06-10 19:49 UTC by marcauberer

Hi,
we're also slowly getting trouble with the server workload due to https encryption, so it would be better to downgrade to HTTP.
Spoiler: We currently work on a new high-performance API, which will be hopefully introduced in the near future.

Are there more changes required than changing the port to 80?

2020-06-17 22:59 UTC, marcauberer commented
Could we merge this pr?
Btw: I don't know why the travis build fails. I did not change significant things. Looks like the Slovakian build does not work.

2020-07-14 15:35 UTC, marcauberer commented
Could we finally merge this?!

2020-08-28 21:05 UTC, dirkmueller commented
This patch is missing the "turning off ssl" part. now you'll simply get the clients send https on port 80, which isn't what you want. 

please change in airrohr-firmware.ino:

```C++
static void createLoggerConfigs() {
...
        loggerConfigs[LoggerFSapp].destport = PORT_FSAPP;
        loggerConfigs[LoggerFSapp].session = new_session();
```

and remove the ".session" line (this will turn off ssl).

2020-08-28 21:05 UTC, dirkmueller requested changes
see earlier comment

2020-08-29 02:06 UTC, marcauberer commented
Done. Should be fine now.

2020-08-29 06:57 UTC, dirkmueller commented
Yes thank you. Now please squash the commits to one ( e.g. git rebase -i HEAD~3 ; git pushf .. )

2020-08-29 06:58 UTC, dirkmueller approved these changes

2020-08-29 14:07 UTC, merged